#include "PlutoGE/scene/NavigationSystem.h"
#include "PlutoGE/scene/Scene.h"
#include <algorithm>
#include <cmath>
#include <limits>
#include <queue>
namespace PlutoGE::scene {
void NavigationSystem::Clear(){m_cells.clear();m_debugPoints.clear();m_width=m_depth=0;}
bool NavigationSystem::Bake(const Scene&s,const NavigationBakeSettings&v){Clear();m_settings=v;m_settings.cellSize=std::max(.1f,v.cellSize);m_width=std::max(1,(int)std::ceil((v.boundsMax.x-v.boundsMin.x)/m_settings.cellSize));m_depth=std::max(1,(int)std::ceil((v.boundsMax.z-v.boundsMin.z)/m_settings.cellSize));if((uint64_t)m_width*m_depth>4000000)return false;m_cells.resize((size_t)m_width*m_depth);float len=std::max(.1f,v.boundsMax.y-v.boundsMin.y),minY=std::cos(glm::radians(std::clamp(v.maxSlopeDegrees,0.f,89.f)));for(int z=0;z<m_depth;++z)for(int x=0;x<m_width;++x){glm::vec3 o{v.boundsMin.x+(x+.5f)*m_settings.cellSize,v.boundsMax.y,v.boundsMin.z+(z+.5f)*m_settings.cellSize};PhysicsRaycastHit h;auto&c=m_cells[(size_t)z*m_width+x];if(s.Raycast(o,{0,-1,0},len,h)&&h.normal.y>=minY){c.walkable=true;c.height=h.point.y;}}
auto source=m_cells;int radius=(int)std::ceil(std::max(0.f,v.agentRadius)/m_settings.cellSize);for(int z=0;z<m_depth;++z)for(int x=0;x<m_width;++x){auto&c=m_cells[(size_t)z*m_width+x];if(!c.walkable)continue;for(int dz=-radius;dz<=radius&&c.walkable;++dz)for(int dx=-radius;dx<=radius;++dx){if(dx*dx+dz*dz>radius*radius)continue;int nx=x+dx,nz=z+dz;if(nx<0||nz<0||nx>=m_width||nz>=m_depth){c.walkable=false;break;}const auto&neighbor=source[(size_t)nz*m_width+nx];if(!neighbor.walkable||std::abs(neighbor.height-c.height)>v.maxStepHeight){c.walkable=false;break;}}}for(int i=0;i<(int)m_cells.size();++i)if(m_cells[i].walkable)m_debugPoints.push_back(CellPosition(i));return !m_debugPoints.empty();}
glm::vec3 NavigationSystem::CellPosition(int i)const{int x=i%m_width,z=i/m_width;return{m_settings.boundsMin.x+(x+.5f)*m_settings.cellSize,m_cells[i].height,m_settings.boundsMin.z+(z+.5f)*m_settings.cellSize};}
int NavigationSystem::FindNearestCell(const glm::vec3&p)const{if(m_cells.empty())return-1;int cx=(int)((p.x-m_settings.boundsMin.x)/m_settings.cellSize),cz=(int)((p.z-m_settings.boundsMin.z)/m_settings.cellSize),best=-1;float bd=std::numeric_limits<float>::max();for(int r=0;r<=8&&best<0;++r)for(int z=cz-r;z<=cz+r;++z)for(int x=cx-r;x<=cx+r;++x){if(x<0||z<0||x>=m_width||z>=m_depth)continue;int i=z*m_width+x;if(!m_cells[i].walkable)continue;glm::vec3 d=CellPosition(i)-p;float q=glm::dot(d,d);if(q<bd){bd=q;best=i;}}return best;}
bool NavigationSystem::ProjectPoint(const glm::vec3&p,glm::vec3&o)const{int i=FindNearestCell(p);if(i<0)return false;o=CellPosition(i);return true;}
bool NavigationSystem::IsSegmentWalkable(const glm::vec3&a,const glm::vec3&b)const{glm::vec3 delta=b-a;delta.y=0;const float distance=glm::length(delta);const int samples=std::max(1,(int)std::ceil(distance/(m_settings.cellSize*.25f)));float previousHeight=a.y;for(int sample=0;sample<=samples;++sample){float t=(float)sample/(float)samples;glm::vec3 point=glm::mix(a,b,t);int x=(int)std::floor((point.x-m_settings.boundsMin.x)/m_settings.cellSize),z=(int)std::floor((point.z-m_settings.boundsMin.z)/m_settings.cellSize);if(x<0||z<0||x>=m_width||z>=m_depth)return false;const auto&cell=m_cells[(size_t)z*m_width+x];if(!cell.walkable||std::abs(cell.height-previousHeight)>m_settings.maxStepHeight)return false;previousHeight=cell.height;}return true;}
NavigationPath NavigationSystem::FindPath(const glm::vec3&a,const glm::vec3&b)const{NavigationPath out;int start=FindNearestCell(a),goal=FindNearestCell(b);if(start<0||goal<0)return out;struct N{int i;float f;bool operator<(const N&o)const{return f>o.f;}};std::priority_queue<N>q;std::vector<float>g(m_cells.size(),std::numeric_limits<float>::max());std::vector<int>parent(m_cells.size(),-1);g[start]=0;q.push({start,0});constexpr int d[8][2]={{1,0},{-1,0},{0,1},{0,-1},{1,1},{1,-1},{-1,1},{-1,-1}};while(!q.empty()){int c=q.top().i;q.pop();if(c==goal)break;int x=c%m_width,z=c/m_width;for(auto&o:d){int nx=x+o[0],nz=z+o[1];if(nx<0||nz<0||nx>=m_width||nz>=m_depth)continue;int n=nz*m_width+nx;if(!m_cells[n].walkable||std::abs(m_cells[n].height-m_cells[c].height)>m_settings.maxStepHeight)continue;if(o[0]&&o[1]){const int sideX=z*m_width+nx,sideZ=nz*m_width+x;if(!m_cells[sideX].walkable||!m_cells[sideZ].walkable)continue;}float ng=g[c]+(o[0]&&o[1]?1.4142f:1.f);if(ng>=g[n])continue;g[n]=ng;parent[n]=c;int gx=goal%m_width,gz=goal/m_width;q.push({n,ng+std::hypot((float)(gx-nx),(float)(gz-nz))});}}if(goal!=start&&parent[goal]<0)return out;for(int i=goal;i>=0;i=parent[i]){out.points.push_back(CellPosition(i));if(i==start)break;}std::reverse(out.points.begin(),out.points.end());if(out.points.size()>2){std::vector<glm::vec3>simplified;simplified.push_back(out.points.front());size_t anchor=0;while(anchor+1<out.points.size()){size_t furthest=anchor+1;for(size_t candidate=out.points.size()-1;candidate>anchor+1;--candidate){if(IsSegmentWalkable(out.points[anchor],out.points[candidate])){furthest=candidate;break;}}simplified.push_back(out.points[furthest]);anchor=furthest;}out.points=std::move(simplified);}if(!out.points.empty()){out.points.front()=a;out.points.back()=b;}out.complete=true;return out;}
}
