export const componentTypes = [
	"MeshComponent",
	"TerrainComponent",
	"FoliageComponent",
	"ClothComponent",
	"ParticleSystemComponent",
	"SplineComponent",
	"OceanComponent",
	"AnimationComponent",
	"CameraComponent",
	"LightComponent",
	"RigidbodyComponent",
	"ColliderComponent",
	"NavAgentComponent",
	"NavigationMeshComponent",
	"IblCaptureComponent",
	"PhysicalSkyComponent",
	"VolumetricCloudComponent",
	"ScriptComponent",
	"SoundEmitterComponent",
	"SoundListenerComponent",
	"CanvasComponent",
	"RectTransformComponent",
	"UIImageComponent",
	"UITextComponent",
	"UIButtonComponent",
];

export const componentCategories: Record<string, string> = {
	MeshComponent: "Rendering",
	TerrainComponent: "Rendering",
	FoliageComponent: "Rendering",
	ClothComponent: "Rendering",
	ParticleSystemComponent: "Effects",
	SplineComponent: "Geometry",
	OceanComponent: "Environment",
	AnimationComponent: "Animation",
	CameraComponent: "Rendering",
	LightComponent: "Rendering",
	RigidbodyComponent: "Physics",
	ColliderComponent: "Physics",
	NavAgentComponent: "Navigation",
	NavigationMeshComponent: "Navigation",
	IblCaptureComponent: "Environment",
	PhysicalSkyComponent: "Environment",
	VolumetricCloudComponent: "Environment",
	ScriptComponent: "Scripting",
	SoundEmitterComponent: "Audio",
	SoundListenerComponent: "Audio",
	CanvasComponent: "UI",
	RectTransformComponent: "UI",
	UIImageComponent: "UI",
	UITextComponent: "UI",
	UIButtonComponent: "UI",
};

export const entityPresets = [
	"Empty Entity",
	"Cube",
	"Camera",
	"Directional Light",
	"Point Light",
	"Sky",
	"Ocean",
	"Terrain",
	"Cloth",
	"Particle System",
	"IBL Capture",
];

export const displayComponentName = (type: string): string =>
	type.replace(/Component$/, "").replace(/([a-z])([A-Z])/g, "$1 $2");
