#pragma once
// Shared by C++ and Slang. Keep addressing and resource sizes in one place.
#define PLUTO_VSM_LEVELS 4
#define PLUTO_VSM_GRID 128
#define PLUTO_VSM_PAGE_SIZE 128
#define PLUTO_VSM_ATLAS_TILES 16
#define PLUTO_VSM_CAPACITY (PLUTO_VSM_ATLAS_TILES * PLUTO_VSM_ATLAS_TILES)
#define PLUTO_VSM_RESOLUTION (PLUTO_VSM_GRID * PLUTO_VSM_PAGE_SIZE)
#define PLUTO_VSM_ATLAS_SIZE (PLUTO_VSM_ATLAS_TILES * PLUTO_VSM_PAGE_SIZE)
#define PLUTO_VSM_LEVEL_PAGES (PLUTO_VSM_GRID * PLUTO_VSM_GRID)
#define PLUTO_VSM_MAX_DRAW_CHUNKS 4096
