#pragma once
// Shared by C++ and Slang. Keep addressing and resource sizes in one place.
#define PLUTO_VSM_FINE_LEVELS 4
#define PLUTO_VSM_ROOT_LEVEL PLUTO_VSM_FINE_LEVELS
#define PLUTO_VSM_DIRECTIONAL_LEVELS (PLUTO_VSM_FINE_LEVELS + 1)
#define PLUTO_VSM_SPOT_COUNT 4
#define PLUTO_VSM_SPOT_GRID 16
#define PLUTO_VSM_SPOT_ROOT_GRID 2
#define PLUTO_VSM_SPOT_ROOT_BASE (PLUTO_VSM_DIRECTIONAL_LEVELS + PLUTO_VSM_SPOT_COUNT)
#define PLUTO_VSM_LEVELS (PLUTO_VSM_DIRECTIONAL_LEVELS + 2 * PLUTO_VSM_SPOT_COUNT)
#define PLUTO_VSM_ROOT_GRID 8
#define PLUTO_VSM_ROOT_PAGES (PLUTO_VSM_ROOT_GRID * PLUTO_VSM_ROOT_GRID)
#define PLUTO_VSM_LEVEL_GRID(level) ((level) >= PLUTO_VSM_SPOT_ROOT_BASE ? PLUTO_VSM_SPOT_ROOT_GRID : ((level) >= PLUTO_VSM_DIRECTIONAL_LEVELS ? PLUTO_VSM_SPOT_GRID : ((level) == PLUTO_VSM_ROOT_LEVEL ? PLUTO_VSM_ROOT_GRID : PLUTO_VSM_GRID)))
#define PLUTO_VSM_GRID 128
#define PLUTO_VSM_PAGE_SIZE 128
#define PLUTO_VSM_ATLAS_TILES 32
#define PLUTO_VSM_DEFAULT_POOL_PAGES 256
#define PLUTO_VSM_STATS_HISTORICAL_AGE 18
#define PLUTO_VSM_STATS_UPDATED_TRIANGLES_BASE 19
#define PLUTO_VSM_STATS_DIRTY_TRIANGLES_BASE (PLUTO_VSM_STATS_UPDATED_TRIANGLES_BASE + PLUTO_VSM_LEVELS)
#define PLUTO_VSM_STATS_MAX_DIRTY_TRIANGLES (PLUTO_VSM_STATS_DIRTY_TRIANGLES_BASE + PLUTO_VSM_LEVELS)
#define PLUTO_VSM_STATS_TRIANGLE_DEFERRED (PLUTO_VSM_STATS_MAX_DIRTY_TRIANGLES + 1)
#define PLUTO_VSM_STATS_PAGE_DEFERRED (PLUTO_VSM_STATS_MAX_DIRTY_TRIANGLES + 2)
#define PLUTO_VSM_COUNTER_COUNT (((PLUTO_VSM_STATS_PAGE_DEFERRED + 64) / 64) * 64)
#define PLUTO_VSM_PAGE_METADATA_BYTES 80
#define PLUTO_VSM_CAPACITY (PLUTO_VSM_ATLAS_TILES * PLUTO_VSM_ATLAS_TILES)
#define PLUTO_VSM_RESOLUTION (PLUTO_VSM_GRID * PLUTO_VSM_PAGE_SIZE)
#define PLUTO_VSM_ATLAS_SIZE (PLUTO_VSM_ATLAS_TILES * PLUTO_VSM_PAGE_SIZE)
#define PLUTO_VSM_LEVEL_PAGES (PLUTO_VSM_GRID * PLUTO_VSM_GRID)
#define PLUTO_VSM_UPDATE_LIST_OFFSET (PLUTO_VSM_LEVELS + PLUTO_VSM_LEVELS * PLUTO_VSM_LEVEL_PAGES)
#define PLUTO_VSM_MAX_DRAW_CHUNKS 4096
// Reserve enough instance indices for every physical page and 64 models.
#define PLUTO_VSM_INSTANCE_STRIDE (PLUTO_VSM_CAPACITY * 64)
